server:
  port: 8080
  retries: 0

  rate_limit:
    rps: 10
    burst: 20

routes:
  - path: /
    strategy: least_connections

    upstreams:
      - url: http://localhost:3001
        weight: 5

      - url: http://localhost:3002
        weight: 3