server:
  port: 8080
  retries: 0

  rate_limit:
    rps: 10
    burst: 20

routes:
  - path: /
    timeout: 5s
    strategy: least_connections

    request_headers:
      add:
        X-Gateway: DUG
        X-Version: v1

      remove:
        - X-Internal

    response_headers:
      add:
        X-Powered-By: DUG

      remove:
        - Server

    upstreams:
      - url: http://localhost:3001
        weight: 5

      - url: http://localhost:3002
        weight: 3