server:
  port: 8080
  retries: 2

  rate_limit:
    rps: 10
    burst: 20

routes:
  - path: /
    upstreams:
      - http://localhost:3001
        weight: 5

      - http://localhost:3002
        weight: 3